### ISSUE TITLE
Consistency of Particle.width and Particle.lifetime

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/particle#185]
As reported by @daritter, there is an inconsistency in the return values / exceptions in `Particle.width` and `Particle.lifetime`. This is due to the fact that the PDG does not always provide width values for all particles, or else it provides -1. How to make things consistent?

Specifically, "there are particles which currently throw a ValueError when accessing lifetime since the width is <0. I'm fine if this is intended. Yes, if we don't know the width we don't have a lifetime but then it would be maybe more consistent to also throw when width<0 as this doesn't make any physical sense either. Or just return NaN in both cases ...".

Opinions @henryiii, @mayou36?

**Comment by daritter** [comment]
Let me clarify the second part: either both, `Particle.lifetime` and `Particle.width` should throw on non-physical values or both should silently return some value (NaN or similar)

**Comment by mayou36** [comment]
agree with @daritter, it should be consistent in both.

Thinking about all the cases, permission vs ask-for-forgiveness, returning simply `None` may does the trick: 

- This will raise an error if used by accident in a calculation (which I prefer over NaN, the latter are hard to track sometimes, e.g. in a reduce sum)
- It seems similar expressive as NaN or an error.

Sure, it has to be caught explicitly (`if Particle.width is not None:`) but this has to be done anyway (otherwise catch the NaN, ask for `has_width` or catch the exception).

So return `None` for lifetime and width if not defined in PDG, what do you think?

**Comment by eduardo-rodrigues** [comment]
I gave this a better thought. We have to keep consistency and preserve the functionality. I was going to implement the return of `None` for `Particle.width` and `Particle.lifetime` but then ran into the issue that powerful searches such as `Particle.findall(lifetime = lambda x : x > 1*second)` will cease to work because you cannot do comparison operations with `None` (> in this case). In the end it may be better to be returning -1 in both properties, which then should be clear that this is a dummy valid when none is available from the PDG table (docstrings to make this clear, of course).

This being said, the standalone functions such as `width_to_lifetime` will still be raising an exception if a negative value is provided, as that's clearly nonsense for the conversion. The method `Particle.lifetime` will catch the exception and will return -1 as said above.

This seems all consistent to me and will preserve the great functionality of the search methods. Is this OK to everyone?

**Comment by henryiii** [comment]
Could you not do it by raising an exception? Then you can easily catch and ignore it in a search function. -1 might not be catchable until it’s too late (such as if it squared, etc).

**Comment by mayou36** [comment]
A squared value is also my concern, but the simplicity of `findall` to be used as e.g. a CL tool seems more important to me here. Catching the exception (or the `None`) makes it impossible to use the short, simple lambdas (which are exactly what you want here).

An alternative thought: we could have an automatic exception catching in the `findall` and rate the error as `False` (is it applicable though logically?). We could have custom errors (e.g. `LifetimeNotDefinedError` and catch *only* the specified, safe ones that can be caught (using the custom Exceptions we do not silence errors raised in the lambda due to user bugs).

**Comment by eduardo-rodrigues** [comment]
OK, folks, this discussion made me scratch my head a bit more :-). I think I have a solution, using None values where indeed there is no value available, and making sure we keep consistency in the width and lifetime values. I will push a PR soon and then you review, OK?

**Comment by mayou36** [comment]
So actually, @henryiii had the same idea as me, just differently formulated (as we found out in an offline chat).

With `None` (I like it since it's clean and clear), how to make `findall` work? We could have an `error_is_false` flag and catch all errors as `False`?

Or we go for the error method and catch the specific errors (but this is not so clear maybe to the user: if you know it can raise an error, why would you expect `Particle.findall(lifetime = lambda x : x > 1*second)` to work? Then we're back again at the `error_is_false` flag kinda)

-> I tend to the None with a flag? (I hate proposing flags though!)
