### ISSUE TITLE
Diquarks not found

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/particle#218]
Pythia likes to make diquark intermediate particles sometimes, and they are listed in the numbering scheme e.g. `(ud)_0 2101` but cannot be constructed:
```
>>> from particle import Particle
>>> Particle.from_pdgid(2101)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ncsmith/Library/Python/3.7/lib/python/site-packages/particle/particle/particle.py", line 756, in from_pdgid
    raise ParticleNotFound("Could not find PDGID {0}".format(value))
particle.particle.particle.ParticleNotFound: Could not find PDGID 2101
```

**Comment by eduardo-rodrigues** [comment]
This is not different from what is reported in https://github.com/scikit-hep/particle/issues/210. In short, this happens because `Particle.from_...` so far only constructs instances from the particles provided by the PDG data table, with extra info we add (plus a few extra particle we curate ourselves).

We can extend the package so that `Particle` instances can also be done for just about all possible types of particles: diquarks, exotics, nuclei. I have some ideas and even an add-on file with info. I just need a bit of time to get the ball rolling with it …

BTW, what's your usecase? I ask this as for example we deal with the issue transparently in `DecayLanguage`. There, all you need are names for particles, their charge-conjugate, and little more. In that case we directly make use of the conversions file that has almost everything, see https://github.com/scikit-hep/particle/blob/master/particle/data/conversions.csv. There are a few objects in `particle.converters` prepared, and other converters can be created on the fly.
So, again, what info will you want from a diquark, for example? Basically info you can get from its PDGID?

**Comment by nsmith-** [comment]
I think much like Hans I just want it to return some data structure with as much information as it can reasonably guess, and `None` where it cannot guess.
In concrete terms I had a pandas dataframe with pdgIds and counts, and I wanted to see nice names and the nominal masses.  Ideally it would be
```python
from particle import Particle
df['name'] = df['pdgId'].apply(lambda i: Particle.from_pdgid(i).name)
```
but rather I end up catching the exception myself:
```python
from particle import Particle, ParticleNotFound

def getname(pdgid):
    try:
        return Particle.from_pdgid(pdgid).name
    except ParticleNotFound:
        return None
    
def getmass(pdgid):
    try:
        return Particle.from_pdgid(pdgid).mass / 1e3
    except ParticleNotFound:
        return None

df['name'] = df['pdgId'].apply(getname)
df['nominalmass'] = df['pdgId'].apply(getmass)
```

**Comment by eduardo-rodrigues** [comment]
At the moment I have no source provider for diquark masses. If these exist in EvtGen or another program you use, can you point me to that info? I would be very glad to add it here. Thanks.

**Comment by nsmith-** [comment]
Hi, sorry for mass indeed all I would expect is `None`.  For those I just want the name.  (which the rebuttal might be" you can deduce by inspecting the number carefully but ok)

**Comment by eduardo-rodrigues** [comment]
I'm finally back to work on the package since I started my new job! Apologies for the terribly long delay.

PR https://github.com/scikit-hep/particle/pull/224 adds info on diquarks. Soon I will add info for other non-standard particles, which is not available through the downloadable PDG .mcd file.

I even added a bit more info on diquarks, so not just the name:
```
In [2]: print(Particle.from_pdgid(2101).describe())
Name: (ud)(0)        ID: 2101         Latex: $(ud)_{0}$
Mass  = ?
Width = ?
Q (charge)        = +1/3    J (total angular) = 0.0      P (space parity) = ?
C (charge parity) = ?       I (isospin)       = 1.0      G (G-parity)     = ?
    Antiparticle name: (ud)(0)~ (antiparticle status: Barred)
```
