### ISSUE TITLE
Unexpected behavior of Particle.from_string

### ISSUE THREAD

**Issue by landerlini** [scikit-hep/particle#241]
When creating a proton from the string "p+", `Particle.from_string` returns a pion instead of a proton.
Things work fine when creating the particle from the string "p". 

**Reproducer**:
```
from particle import Particle
proton = Particle.from_string ("p+")
print (proton.name)  ## output: "pi+"
```

**Acceptable solution**:
The ability of Particle of trying to match particles by name without exact match is great, but when nested into other application wrong matches may result in tedious bugs difficult to debug. 
I would suggest to add an optional boolean flag to the "from_string" to allow raising an error in case of an imperfect match.

**Comment by eduardo-rodrigues** [comment]
Thanks for getting in touch and using the package, @landerlini.

I see  your worry. Talking for myself, I personally reckon that this `from_string` method can probably be deprecated given all recent-ish developments. After all, there is a reason why the method is not even mentioned in the README. The method is there largely for historical reasons. Really, you can do much more powerful searches with `find` and `findall`.

Why do you not rather do `Particle.find(evtgen_name='p+')` for example? Since you mention `p+` as a name, I assume you look for particle names in decay files. This statement is far more explicit than your example. Also, it does throw an exception when there is more than one match found, and you can search with many particle properties, including with lambda functions …

Let me know a bit more what you want to do. In the end we should strive to have users run the package in the best way possible :-).

**Comment by eduardo-rodrigues** [comment]
Also, please have a look at the docstring of `from_string`. It does says "Get a particle from a PDG style name - returns the best match." and that's probably not what you need since, again, you mention `p+` whereas the proton name is just `p`. Let me know ...

**Comment by landerlini** [comment]
Ciao @eduardo-rodrigues, I wrapped this functionality of Particle into an application of mine order 1 year ago using "from_string", and it has been working like a charm till today when I misprinted "p+" instead of "p" and got unreasonable results from my application. Digging and digging I found the reason was my misprint. 
I have included the check on the returned particle name in my own code.

I am indeed more used to EvtGen name scheme, so I will have a look to find which could allow using the same symbols as LHCb LoKi reducing my memory effort.

Thanks!

**Comment by eduardo-rodrigues** [comment]
No probs. We certainly use the official EvtGen names so should really be 100% the same as for LoKi.

I'm glad to see the package used by LHCbers, and very glad that you (seem to) like it :-).

Do not hesitate to get in touch for how to best use the package. We can try and improve the doc based on user feedback ...

**Comment by landerlini** [comment]
>  very glad that you (seem to) like it
I certainly do!
