### ISSUE TITLE
Bug report: both baryons and antibaryons have parity +1

### ISSUE THREAD

**Issue by redeboer** [scikit-hep/particle#250]
Hello scikit-heppers,
Thanks for creating this nice package! It provides a useful interface to the PDG.

We are considering to use this package in the [`expertsystem`](https://pypi.org/project/expertsystem) package, but noticed a potential bug while trying to implement it (https://github.com/ComPWA/expertsystem/pull/190): it seems that all baryons and antibaryons have parity +1.

For example, in the following, both have `P (space parity) = +`:

```bash
python3 -m particle search 2212  # proton
python3 -m particle search -2212  # anti-proton
```

For a list of anti-baryons that (I guess) should have parity -1, see:

```python
from particle import Particle

Particle.findall(lambda p: p.pdgid.is_baryon and p.pdgid < 0 and p.P == +1)
```

This seems to be the case in both the [latest release](https://github.com/scikit-hep/particle/releases/tag/v0.10.0) and the latest commit cae76410d6c45e8c2df4982ae6edb6735c544b41.

**Comment by eduardo-rodrigues** [comment]
Thank you for reporting! Good catch! I really wonder how we never realised that. It must be that we have no test for it and the extended file that provides things such as parity (not available in the standard .mcd file from the PDG) is not being digested properly for baryons. I will look into this asap ...

**Comment by eduardo-rodrigues** [comment]
BTW @redeboer, you are more than welcome to contribute to this package to augment what is provided by `Particle`and/or `PDGID`. I have myself a list of small bits of functionality that could be added at some point but maybe your package has extra needs? We can discuss this in a separate "issue" if you like.

**Comment by redeboer** [comment]
Thanks, sounds good!
Internally, our package is just about propagating quantum numbers through a decay topology. Eventually, that decay topology is converted into an amplitude model for Partial Wave Analysis. It's only at the 'outer edges' of that topology -- the initial and final state -- that more general particle info like particle names comes into play (for the user interface). Practically speaking: we only require (conservation of) quantum numbers, which may clash with the concept of the `particle.Particle` class, because that contains more general information, like anti-particle and quark content.

But for sure I'll go through your source code if there I run into other issues, or post issues if I have some ideas!

**Comment by redeboer** [comment]
One general thought I had (and I'll post it here, because not sure whether it's worth an issue): why does the `Particle` class serve both as a sort of database class and a container for the individual particle info instances? Initially, I had trouble to understand how the class behaved, because it seems to have many responsibilities under the surface. The same goes for `PDGID`, which can for instance be used both for comparison to `int`, but also contains several other attributes like `has_charm`.

**Comment by eduardo-rodrigues** [comment]
These are design choices.  Take the `PDGID` class: it makes sense to have the ID as a class since it can "answer" a series of questions such as charge, is_baryon, etc. It should also be comparable with an int, of course. Now, we also provide the same is_baryon/... functions as free functions, just as the HepPID C++ package does. This seems all fair and most useful, covering the different use cases that people may have.

The same goes for the `Particle` class. Clearly you want to have an entity (=object) wrapping all kinds of info relevant for a particle, and it be able to answer standard questions. The fact that the class serves also as a kind a database, as you say, is necessary to (1) make it the easiest for the standard user and (2) avoid too much code for no benefit. If the loading of the default information was not done for you, and via the same class, how would you do it? Every single user would have to first load the table/DB/info from somewhere and the `Particle` class would have to connect to it somehow for every query. This would be rather cumbersome.

So far the feeback has been very good that people like both the functionality of the `Particle` class and the super flexible searches one can perform :-).

But I'm always happy to hear suggestions. Thanks.

**Comment by redeboer** [comment]
Thanks for your accurate answer!
I have to think about the design choice, it feels like it's going against established principles like SRP. But I admit I'm rather new to 'Pythonic thinking' and am for instance not yet sure about what is considered 'correct' use of class attributes vs instance attributes.

At any rate, I agree that the package works nicely and indeed like the flexible searches it provides!

**Comment by eduardo-rodrigues** [comment]
FYI @redeboer the release 0.11.0 with the bug fixed is out, see https://github.com/scikit-hep/particle/releases/tag/v0.11.0 :-).
