### ISSUE TITLE
Vectorised lookup

### ISSUE THREAD

**Issue by jacanchaplais** [scikit-hep/particle#348]
Hi there,

Love the project. Just wondering whether there is a way to use something like `from_pdgid` with an iterable of integers. Instantiating a new particle object for each is very expensive, and if I'm just trying to quickly look up a restricted selection of properties en masse it isn't very practical for my use case.

Kind regards,
Jacan.

**Comment by henryiii** [comment]
You don't instantiate a new object for each; they are already instantiated in a table and you are just pulling them out. The only cost is the search for the PDGID, which is a little expensive - we don't assume anything about PDGID and use it as a hash, for example - it's a linear search. If you have a limited subset you are interested in, you could cache these in a dictionary and that would be a bit faster; probably we could optimize this a bit.

**Comment by henryiii** [comment]
Can you see if #349 is faster for you?

**Comment by eduardo-rodrigues** [comment]
Hi. Also, can you explain a bit better what you are trying to do? If you want a retricted selection then calls such as `Particle.finditer(lambda p: p.pdgid.is_meson and p.pdgid.has_charm and p.spin_type==SpinType.PseudoScalar)` might be your friend. (BTW, I realise that we need to document this new iterator method better since the README rather talks about `Particle.findall`.)

**Comment by jacanchaplais** [comment]
Apologies for the delay - is this for looking up a single particle? My concern was primarily that I may want to look up many particles by their pdgid. For instance, if I have a few hundred particles in my final state, and wish to view all of their names, I could do something like

```python
pdg_ids = [1, 211, ..., 12]
names = [Particle.from_pdgid(pdg) for pdg in pdg_ids]
```

but this would instantiate a particle object for each id, no?

For my own purposes, I have solved the issue by downloading the CSV file and load it into pandas, then find the unique pdgs and query the table for their names (and other properties), but I wanted to offer some elaboration on the functionality I was asking about.

Thanks again for the great work on this library and dataset!

Kind regards,
Jacan.

**Comment by jacanchaplais** [comment]
Code viewable here:
https://github.com/jacanchaplais/mcpid/blob/main/mcpid/lookup.py

I will credit you when I write a README, and in my research! :)

Jacan.

**Comment by eduardo-rodrigues** [comment]
Hi @jacanchaplais, we provide this package "precisely" (there are other reasons) to avoid having each and single colleague perform the same kind of manipulations. It would be useful to understand how exactly and what for your are extracting particle information, and I doubt that you can make it much faster, unless you do something totally tailored. And, generally speaking, if would be profitable if you contribute to the package for the benefit of all if you find some relevant enhancement.

Apologies for the delay - is this for looking up a single particle?

What is looking up a single particle? As mentioned by @henryiii the table is built once and for all, just as you have to make your dataframe. There is no major waste of time afterwards in the sense that you are simply accessing info from the loaded table.

> My concern was primarily that I may want to look up many particles (including duplicates) by their pdgid.

Depending on your usecase you could even get a whole bunch in one go, say `Particle.findall(lambda p: p.pdgid > 20 and p.pdgid < 1000)` for the sake of argument (same signature with `finditer`). Or `Particle.findall(lambda p: p.pdgid in [1, 211, 12])` or ...

You mean duplicates in your code, right? Because we have none by constructions in our tables. And if you digest lots and lots of info you may want to have a little LRU cache?

> For instance, if I have a few hundred particles in my final state, and wish to view all of their names, I could do something like

> pdg_ids = [1, 211, ..., 12]
names = [Particle.from_pdgid(pdg).name for pdg in pdg_ids]
but this would instantiate a particle object for each id, no?

Got me curious - can you provide an example of "few hundred particles in my final state"?

> For my own purposes, I have solved the issue by downloading the CSV file and loading it into pandas, then finding the unique pdgs and querying the dataframe for their names (and other properties), but I wanted to offer some elaboration on the functionality I was asking about.

Again, we provide functionality to do this trivially. If you let us know better what are your "end-user" lines where you extra particle info we can see better if there is something else we can do.

You love the project you say? We love to "see that" with GitHub stars = likes ;-).

**Comment by jacanchaplais** [comment]
Hi Eduardo,

Thank you for the response! I definitely am under no allusions that my scrappy single file module, which just wraps a pandas DataFrame of your CSV, is anywhere near as sophisticated and optimised as your project. I think I may have not fully understood the functionality, and assumed the use case you were catering for was a little different to mine.

I will explore the other class methods and if it appears I am missing the functionality I'm after, I'll make a more detailed and informed contribution.

Noted, starred the project. ;P

Thanks for the help,
Jacan.

**Comment by henryiii** [comment]
I would try `df["name"] = df["pdgid"].apply(lambda x: Particle.from_pdgid(x).name)`. It should be reasonably fast. If it needs to be faster, there could be options, but I'd try that first and see if it's fast enough.

**Comment by eduardo-rodrigues** [comment]
Congrats, you're the 100th star 👍 !
