### ISSUE TITLE
No SUSY particles in this package?

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/particle#371]
```python
>>> particle.Particle.from_pdgid(1000024).name
*** particle.particle.particle.ParticleNotFound: Could not find PDGID 1000024
```

Will there be support for the susy particles?

**Comment by eduardo-rodrigues** [comment]
I recently-ish had the same discussion at https://github.com/scikit-hep/particle/issues/346. Have a look at my comments and I welcome feedback as you're not the 2nd nor the 3rd to ask about this.

In a way you can't do the above because you don't really have info to create an unknown particle as in the PDG, hence the converters you will see in the discussion ...
