### ISSUE TITLE
spin of SUSY partners

### ISSUE THREAD

**Issue by yorkiva** [scikit-hep/particle#463]
While checking out the package, I found that some of the SUSY partners of the SM quarks are assigned a spin value of 2 (that in the 2s+1 scheme represents a spin-1/2 particle). For instance, the left-handed partner of up-quark `suL`, which is usually represented by id 1000002, is assigned a value of 2 for its `j_spin`. 
But the squarks are bosons, so their spins are integral and should be 1 or 3.

Am I missing something? Please let me know if this is a known (and intentional) issue.

**Comment by eduardo-rodrigues** [comment]
Hello @yorkiva, thank you for the interest in the package.

Hmm, as some people may say, what is not tested is not supported. The longer explanation is useful: we take PDG IDs from the PDG, by definition, of course, and also adapted the C++ codes around to deal with these IDs. In fact we enhanced very much ... But SUSY IDs have not been given a huge scrutiny so far, clearly, and you are right. Somehow various bits of code / PID related functions deal with SUSY IDs but not the spin function! I myself did not notice it because the tests for SUSY particles are not massive. We ought to change that.

The defined particles are all at https://github.com/scikit-hep/particle/blob/master/src/particle/data/conversions.csv. So we should adapt the j_spin function to deal with SUSY IDs, all of them. Would you like to contribute to the package with such an enhancement? That would be great.

Please let us know. Otherwise we will work on this as time permits.

**Comment by yorkiva** [comment]
Hi @eduardo-rodrigues,

Thanks for taking a look. Yes, I would love to help with the modifications. I can start on this only next week though. I will get in touch once I start with this and we can discuss on what parts to modify to make this work.

Regards,
Avik

**Comment by eduardo-rodrigues** [comment]
Kind ping @yorkiva to re-check your interest.

**Comment by amanmdesai** [comment]
Hello @eduardo-rodrigues I would be happy to contribute to this issue in case the issue is still open for contributions.

**Comment by eduardo-rodrigues** [comment]
Hello @amanmdesai. That's great 👍! Indeed nobody is on this.

It may be necessary to get in touch with the PDG to understand exactly how the ID numbers for SUSY particles should be interpreted. I do not know of any piece of code, notably the original C++ libraries dealing with PDG IDs, that deal with this issue, actually.
