### ISSUE TITLE
Missing isospin for h(1)(1415) ?

### ISSUE THREAD

**Issue by redeboer** [scikit-hep/particle#486]
Could it be that $h_1(1415)$ is missing isospin? PDG for reference:
https://pdglive.lbl.gov/Particle.action?init=0&node=M109&home=MXXX005

https://github.com/scikit-hep/particle/blob/817a0f63d9226dac38a688cce73f918dedf9d95f/src/particle/data/particle2022.csv#L337

https://github.com/scikit-hep/particle/blob/817a0f63d9226dac38a688cce73f918dedf9d95f/src/particle/data/particle2022.csv#L2

Bumped into it while investigating https://github.com/ComPWA/qrules/issues/165

**Comment by eduardo-rodrigues** [comment]
Hey both, thanks for the message. I'm over-busy today and will look carefully but indeed the PDG info so far provides
```
In [6]: print(Particle.from_name("h(1)(1415)").describe())
Name: h(1)(1415)     ID: 10333        Latex: $h_{1}(1415)$
Mass  = 1416 ± 8 MeV
Width = 90 ± 15 MeV
Q (charge)        = 0       J (total angular) = 1.0      P (space parity) = +
C (charge parity) = -       I (isospin)       = None     G (G-parity)     = -
    SpinType: SpinType.Axial
    Quarks: x(uU+dD)+y(sS)
    Antiparticle name: h(1)(1415) (antiparticle status: Same)
```

Most likely the PDF ".mcd" we rely on does not provide I, and we do not "add the info by hand". I put this in quote because we do add a bunch of info ourselves in the package, but care is needed.

Note that the 2023 update from the PDG is probably going to be out soon-ish, typically in May. We will see what updates that has :-).

Back asap with more details.

**Comment by mmikhasenko** [comment]
FYI, some preview for the upcoming PDG API is [here](https://indico.cern.ch/event/1179424/contributions/5097604/attachments/2541325/4374907/SCPuReAndMachineReadableData-Adv.pdf)

**Comment by eduardo-rodrigues** [comment]
Hey folks, so I did a bit of digging. Indeed the source of the missing info is 2-fold:

- The extended information we use is that PDG file from 2008 and which point several particles were not established. Otherwise the year PDG tables do not provide isospin and a bunch of other info, which we add via the package basing on the 2008 extended file (I have plans to extend myself info but that takes time and requires care as you can imagine).
- In the meantime the particle actually changed name, as seen on the PDG site you mention above, which does not make matching "easy".

For reference here are the h mesons in the "table":
```
In [1]: from particle import *
In [2]: for p in Particle.finditer(lambda p: "h(" in p.name):
   ...:     print(f"{p.name}: \tPDGID={int(p.pdgid)} \t I={p.I}")
   ...:
h(1)(1170):     PDGID=10223      I=0.0
h(1)(1415):     PDGID=10333      I=None
h(c)(1P):       PDGID=10443      I=None
h(b)(1P):       PDGID=10553      I=0.0
```

How important and/or urgent is it for you to have the particle with isospin information available? I could make a little update to the package for that.

**Comment by eduardo-rodrigues** [comment]
Thank you @mmikhasenko for the link to that PDG presentation. Really useful! I had been in chats with Juerg in the past and it seems I should talk to him again - was easier the one time he was at CERN.

BTW, let me know if you have any thoughts on the "business" (by email if you prefer) as it will be useful for sure. Actually some of the material is more relevant for the DecayLanguage package.

**Comment by eduardo-rodrigues** [comment]
> Not that urgent, I posted a solution for modifying the particle database in the downstream package :)

I guess you suggested to do `p.I = 0.` :).

OK, so not urgent. This being said you gave me more motivation to try and find time. Did one ever say that user feedback *really* is important :)!

**Comment by eduardo-rodrigues** [comment]
BTW, by the time I move to improved tables I am hoping to provide more info, maybe a notebook, so that users can more easily contribute and help.
