### ISSUE TITLE
Missing parity for K(2)*(1980)~0

### ISSUE THREAD

**Issue by MartinTum** [scikit-hep/particle#616]
I realized that in the particle database K(2)*(1980)~0 and its antiparticle are missing their parity, see lines 601 and 602 in https://github.com/scikit-hep/particle/blob/master/src/particle/data/particle2024.csv (assuming that `5` means no information)
In the PDG the parity seems to be well defined: https://pdg.lbl.gov/2024/web/viewer.html?file=../listings/rpp2024-list-K2-star-1980.pdf

Cheers,
Martin

**Comment by eduardo-rodrigues** [comment]
Hi. Thank you for the interest in the package.

You are right. You can easilyc check via
```
In [1]:  from particle import Particle

In [2]: print(Particle.from_pdgid(9010315).describe())
Name: K(2)*(1980)0   ID: 9010315      Latex: $K_{2}^{*}(1980)^{0}$
Mass  = 1990 + 60 - 50 MeV
Width = 348 + 50 - 30 MeV
Q (charge)        = 0       J (total angular) = 2.0      P (space parity) = None
C (charge parity) = None    I (isospin)       = 0.5      G (G-parity)     = None
    Quarks: dS
    Antiparticle name: K(2)*(1980)~0 (antiparticle status: Barred)
```

There are in fact other bits of info (internal quantum numbers) to be added, see for example https://github.com/scikit-hep/particle/issues/486. That' related to the fact that we take info from the PDG and their extended table was only produced in 2008 and we have been adding internal quantum number info manually since then. That does not happen often as it is time consuming, as you can imagine.

I plan to deal with this more extensively towards the end of the month unless somebody beats me to it.

**Comment by eduardo-rodrigues** [comment]
Closed via https://github.com/scikit-hep/particle/pull/621.
