### ISSUE TITLE
from_nucleus_info and from_name inconsitency

### ISSUE THREAD

**Issue by maxnoe** [scikit-hep/particle#620]
I.e. this does not round-trip, which is very surprising:

```
In [55]: p = Particle.from_nucleus_info(a=1, z=1)

In [56]: Particle.from_name(p.name)
---------------------------------------------------------------------------
ParticleNotFound                          Traceback (most recent call last)
Cell In[56], line 1
----> 1 Particle.from_name(p.name)

File ~/.local/conda/envs/cta-dev/lib/python3.11/site-packages/particle/particle/particle.py:1003, in Particle.from_name(cls, name)
   1001     return particle
   1002 except ValueError:
-> 1003     raise ParticleNotFound(f"Could not find name {name!r}") from None

ParticleNotFound: Could not find name 'p'
```

**Comment by eduardo-rodrigues** [comment]
Hi @maxnoe. Thank you for stress-testing the package :-).

So, the reason for these 2, and only 2, exceptions (well, double to accout for their antiparticles), is what @HDembinski replied to you at https://github.com/scikit-hep/particle/issues/263#issuecomment-2326052635. Basically, protons and neutrons can be "seen" as both particles and nuclei, hence the exceptions of non-unique PDG IDs for them.

I think there is no way out, as otherwise one would need to remove all nuclei info.

But you are totally right that, for the sake of argument, the "particle proton" and the "nucleus proton", with different PDG IDs, should compare to equal. And a fix will resolve this issue by construction since the round-trip works, as it should, for all other particles.

Would you be interested in making a contribution for the fix? That would be cool.

**Comment by maxnoe** [comment]
Yes, sure, happy to make a PR. Could you maybe roughly point me into the right general direction?

for the comparison part, I guess overloading `__eq__` on Particle (and PDGID?)?

**Comment by eduardo-rodrigues** [comment]
Yep. Unfortunately the PR will not be tiny because one needs to overload the various comparison operators for Particle. I don't think one should change the PDGID class comparison methods because the PDGIDs *are* different, albeit refering to the same particle.
