### ISSUE TITLE
add "name" function to pdgid/functions.py

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#8]
There is no function in pdgid/functions.py which returns the name of the particle with a given PDGID. I think there should be such a function and I would also like the `__repr__` of PDGID show this name. The name should be generated from the tables in data.

**Comment by HDembinski** [comment]
ok fair enough. but can the repr then show the particle name?

**Comment by eduardo-rodrigues** [comment]
How do you see a PDGID? It really is an integer with certain rules. And the PDGID wrapper class is just a neat way to have the ID be able to reply to the many relevant questions collected in the functions module.

Are you sure you are not rather interested in what is the Particle class, which is what Henry will commit very soon? We can add code to be able to show a particle name in the PDGID, but then the class become much less lightweight because the creation of any PDGID would need to read some long file, and I am not quite seeing the usage. Can you give a concrete example?

I'm not against discussion at all, BTW. Really trying to understand. From what I understand I would say that's more the kind of thing I would do with a Particle.


Thanks.

**Comment by HDembinski** [comment]
I realized in the meantime that the particle class provides the functionality I was expecting. I understand now that PDGID is a low-level ID object, while particle is the high-level object which provides all this meta-data I often want to request, such as particle name, mass, ctau, etc. This is fine.

**Comment by eduardo-rodrigues** [comment]
Precisely - different classes//"things" for different purposes.
